//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class CentreInformatique
{
    // Propriétés
    #region
    public virtual int num_centre
	{
		get;
		set;
	}

	public virtual string adresse_centre
	{
		get;
		set;
	}

	public virtual int cpl_centre
	{
		get;
		set;
	}

	public virtual string ville_centre
	{
		get;
		set;
	}

	public virtual string tel_centre
	{
		get;
		set;
	}

	public virtual Contrat Contrat
	{
		get;
		set;
	}

	public virtual Equipement Equipement
	{
		get;
		set;
	}

	public virtual Client Client
	{
		get;
		set;
	}

	public virtual Secteur Secteur
	{
		get;
		set;
	}
    #endregion Propriétés


    // Constructeurs
    #region 
    public CentreInformatique()
    {

    }

    public CentreInformatique(int numceinfo, string adrceinfo, int cpceinfo, string vilceinfo, string telceinfo,
            Client clceinfo)
    {
        num_centre = numceinfo;
        adresse_centre = adrceinfo;
        cpl_centre = cpceinfo;
        ville_centre = vilceinfo;
        tel_centre = telceinfo;
        Client = clceinfo;
    }
    #endregion Constructeurs

    // Méthodes
    #region Méthodes
    public override string ToString()
    {
        return string.Format("{0}, {1}, {2}, {3}", num_centre, Client.nom_client, adresse_centre, ville_centre);
    }

    public override bool Equals(object cti1)
    {
        if (cti1 is CentreInformatique)
            return
                ((CentreInformatique)cti1).num_centre.Equals(this.num_centre);
        else
            return false;
    }
    #endregion

}

