//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Contrat
{
	public virtual int num_contrat
	{
		get;
		set;
	}

	public virtual double montant_contrat
	{
		get;
		set;
	}

	public virtual DateTime date_validite_contrat
	{
		get;
		set;
	}

	public virtual DateTime date_echeance_contrat
	{
		get;
		set;
	}

	public virtual DateTime date_resiliation_contrat
	{
		get;
		set;
	}

	public virtual string commentaire_contrat
	{
		get;
		set;
	}

	public virtual sbyte statut
	{
		get;
		set;
	}

	public virtual Client Client
	{
		get;
		set;
	}

    public virtual CentreInformatique Centre
    {
        get;
        set;
    }

    public Contrat()
    {

    }

    public Contrat(int numct, double mtct, DateTime dtvalct, sbyte stct, Client clct, 
        CentreInformatique cti)
    {
        num_contrat = numct;
        montant_contrat = mtct;
        date_validite_contrat = dtvalct;
        statut = stct;
        Client = clct;
        Centre = cti;
    }

    public Contrat(int numct, double mtct, DateTime dtvalct, sbyte stct, Client clct,
        CentreInformatique cti, string comm)
    {
        num_contrat = numct;
        montant_contrat = mtct;
        date_validite_contrat = dtvalct;
        statut = stct;
        Client = clct;
        Centre = cti;
        commentaire_contrat = comm;
    }

    public override string ToString()
    {
        string st = null;
        switch (statut)
        {
            case 1:           
                st = "En cours";
                break;
            case 2:
                st = "Renouvelé";
                break;
            case 3:
                st = "Résilié";
                break;

        }
            
        return string.Format("Contrat : {0}, Client : {1}, Centre : {2}, Date d'écheance : {3}, Statut : {4}", 
            num_contrat, Client.nom_client, Centre.adresse_centre, date_echeance_contrat.ToShortDateString(), st);
    }

    public override bool Equals(object ct1)
    {
        if (ct1 is Contrat)
            return
                ((Contrat)ct1).num_contrat.Equals(this.num_contrat);
        else
            return false;
    }

    public DateTime CalculDateEch()
    {
        date_echeance_contrat = date_validite_contrat.AddYears(1);
        return date_echeance_contrat;
    }
}

