//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Equipement
{
	public virtual int num_equip
	{
		get;
		set;
	}

	public virtual string libelle_equip
	{
		get;
		set;
	}

	public virtual sbyte planification_inter_equip
	{
		get;
		set;
	}

	public virtual Contrat Contrat
	{
		get;
		set;
	}

}

