//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Modele
{
	public virtual int num_modele
	{
		get;
		set;
	}

	public virtual string libelle_modele
	{
		get;
		set;
	}

	public virtual Tarif Tarif
	{
		get;
		set;
	}

	public virtual IEnumerable<Equipement> Equipement
	{
		get;
		set;
	}

}

