//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Secteur
{
	public virtual int num_secteur
	{
		get;
		set;
	}

	public virtual string libelle_secteur
	{
		get;
		set;
	}

}

