//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Tarif
{
	public virtual int num_tarif
	{
		get;
		set;
	}

	public virtual DateTime date_tarif
	{
		get;
		set;
	}

	public virtual decimal tarif_modele
	{
		get;
		set;
	}

}

